# Pre-pull all enabled Supabase services in CI
FROM supabase/postgres:15.1.0.89 AS postgres
FROM supabase/realtime:v2.29.5 AS realtime
FROM supabase/gotrue:v2.121.0 AS auth
FROM supabase/storage-api:v0.44.7 AS storage
FROM supabase/postgrest:v11.2.0 AS postgrest

# Final dummy stage to satisfy Docker
FROM alpine

